name: CI/CD with Aqua Trivy Scan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_and_scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Make gradlew executable
        run: chmod +x Demo/gradlew

      - name: Set up Gradle
        uses: gradle/wrapper-validation-action@v1

      - name: Set up Gradle
        uses: gradle/wrapper-validation-action@v1

      - name: Change to Demo directory
        run: cd Demo && ls -l  # Verify gradlew is present

      # Build the project using Gradle Wrapper
      - name: Build the JAR file
        run: cd Demo && ./gradlew build

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: ./Demo
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ghcr.io
          repository: ${{ github.repository_owner }}/demo
          tag_with_ref: true

       # Install Trivy
      - name: Install Trivy
        run: |
          sudo apt-get update
          sudo apt-get install -y wget
          wget https://github.com/aquasecurity/trivy/releases/download/v0.29.2/trivy_0.29.2_Linux-64bit.deb
          sudo dpkg -i trivy_0.29.2_Linux-64bit.deb

      # Check if Trivy is installed
      - name: Check if Trivy is installed
        run: which trivy || echo "Trivy is not installed"
          
      - name: Download Trivy DB (first run)
        run: |
         trivy image --download-db-only ghcr.io/aquasecurity/trivy-db:2
         continue-on-error: true
         
      - name: Scan Docker image with Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image: ghcr.io/${{ github.repository_owner }}/demo:latest
          format: 'sarif'
          output: 'trivy-report.sarif'
          severity: 'HIGH,CRITICAL'

      - name: Upload SARIF report
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: trivy-report.sarif
