name: CI/CD with Aqua Trivy Scan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_and_scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Make gradlew executable
        run: chmod +x Demo/gradlew

      - name: Set up Gradle
        uses: gradle/wrapper-validation-action@v1

      - name: Set up Gradle
        uses: gradle/wrapper-validation-action@v1

      - name: Change to Demo directory
        run: cd Demo  # Ensure we are in the correct directory

      - name: Build the JAR file
        run:  ./gradlew build 

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: ./Demo
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ghcr.io
          repository: ${{ github.repository_owner }}/demo
          tag_with_ref: true

      - name: Scan Docker image with Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image: ghcr.io/${{ github.repository_owner }}/demo:latest
          format: 'sarif'
          output: 'trivy-report.sarif'
          severity: 'HIGH,CRITICAL'

      - name: Upload SARIF report
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: trivy-report.sarif
